### ISSUE TITLE
new anthropometric indicators:  (1)  lightness , (2)  height-to-mass ratio 

### ISSUE THREAD

**Issue by kliegl** [WorldHealthOrganization/anthro#50]
This is a feature request. Would it be possible to provide age- and sex-adjusted z-scores and percentiles also for:

(1) lightness = 1 /  weight
(2) height-to-mass ratio =  height/weight ?

Reason: I would like to replace the transformations used in this paper with age-/sex-adjusted z-scores.
https://www.researchgate.net/publication/377692841_Impact_of_Height-to-Mass_Ratio_on_Physical_Fitness_of_German_Third-Grade_Children.

Thank you.

**Comment by eborghi** [comment]
Dear @kliegl, Thank you for your question. Please note this is a WHO macro and refers to the WHO Child Growth Standards. WHO does not have any standard or recommendation for the use of the indicators you propose. Perhaps in the future! Best, Elaine
