### ISSUE TITLE
Head circumference z scores not being produced

### ISSUE THREAD

**Issue by jgirsc** [WorldHealthOrganization/anthro#51]
I am relatively new to using R but have used the anthro package to calculate z-scores for weight-for-age, length/height-for-age, and BMI-for-age for children under the age of 2 years. In the readme file - it says that the z-score for head circumference-for-age should also be an output, but despite entering head circumference measurement, a z-score is not output.

**Comment by joaodubas** [comment]
@jgirsc can you share the way you are calling the module?

Running the code with these values:

```R
anthro_zscores(
  sex = c(1),
  age = c(731),
  weight = c(12.0),
  lenhei = c(88.5),
  headc = c(47.2),
  armc = c(15.4),
  triskin = c(7.2),
  subskin = c(5.5)
)
```

I see the head circumference z-score:

```R
  clenhei     cbmi cmeasure csex zlen flen  zwei fwei  zwfl fwfl  zbmi fbmi
1    88.5 15.32127     <NA>    1 0.45    0 -0.11    0 -0.54    0 -0.58    0
    zhc fhc  zac fac   zts fts   zss fss
1 -0.77   0 0.21   0 -0.32   0 -0.42   0
```

**Comment by dirkschumacher** [comment]
Thanks @joaodubas. I will close the issue for now.

**Comment by jgirsc** [comment]
OFFICIAL

Thank you so much for follow up on this. After further investigation I can report the error was mine.
I am a very inexperience R user and have been working (struggling) with both the Anthro and the WHOanthro packages - and it is the WHOanthro that doesn't produce the head circumference z-scores.
It is unclear from the WHOanthro documentation whether it is supposed to, in one section of the documentation it says it does, and in another, it is not mentioned.
But I have now been able to produce them using Anthro.
Thanks again,
Jennifer
